blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/martrapp/astro-vtbot/issues/new?template=feature-request.yml
    about: Want to be able to pull a new trick ✨ out of the bag 👜? Use this link.
  - name: GitHub Discussions
    url: https://github.com/martrapp/astro-vtbot/discussions
    about: Does the issue involve a lot of explanation, or are you not sure how it can be split into actionable tasks? Consider starting a discussion first.
